#!/usr/bin/env bash
set -euo pipefail

obsidian_root="/home/donovan/Documents/Obsidian"
atlas_root="/home/donovan/Documents/Obsidian/pytheas/Operations/Vault Atlas"
vaults=(agonizing-sentience finance learning life pytheas)
atlas_date="$(date +%F)"

mkdir -p "$atlas_root"

for vault in "${vaults[@]}"; do
  vault_root="$obsidian_root/$vault"
  output="$atlas_root/$vault.md"
  {
    echo '---'
    echo "title: Vault Atlas — $vault"
    echo "date: $atlas_date"
    echo 'type: generated-vault-atlas'
    echo "vault: $vault"
    echo '---'
    echo
    echo "# Vault Atlas — $vault"
    echo
    echo '> Generated by `scripts/generate-vault-atlas.sh`. `.git/` internals are excluded; hidden vault files are included; symlinks are recorded but not traversed.'
    echo
    echo '## Summary'
    echo
    printf -- '- Folders: %s\n' "$(find "$vault_root" -path "$vault_root/.git" -prune -o -type d -print | wc -l)"
    printf -- '- Files: %s\n' "$(find "$vault_root" -path "$vault_root/.git" -prune -o -type f -print | wc -l)"
    printf -- '- Symlinks: %s\n' "$(find "$vault_root" -path "$vault_root/.git" -prune -o -type l -print | wc -l)"
    echo
    echo '## Complete path inventory'
    echo
    echo '| Type | Path | Bytes | Modified |'
    echo '|---|---|---:|---|'
    {
      if [[ "$vault" == "pytheas" ]]; then
        find "$vault_root" \
          -path "$vault_root/.git" -prune -o \
          -path "$atlas_root" -prune -o \
          -mindepth 1 -printf '%y\t%P\t%s\t%TY-%Tm-%Td %TH:%TM\n'
        printf 'd\tOperations/Vault Atlas\t-\tgenerated\n'
        find "$atlas_root" -mindepth 1 -maxdepth 1 -type f \
          -printf 'f\tOperations/Vault Atlas/%f\t-\tgenerated\n'
      else
        find "$vault_root" -path "$vault_root/.git" -prune -o \
          -mindepth 1 -printf '%y\t%P\t%s\t%TY-%Tm-%Td %TH:%TM\n'
      fi
    } | LC_ALL=C sort -t $'\t' -k2,2 \
      | while IFS=$'\t' read -r kind path bytes modified; do
          case "$kind" in
            d) label='folder' ;;
            f) label='file' ;;
            l) label='symlink' ;;
            *) label="$kind" ;;
          esac
          escaped_path=${path//|/\\|}
          printf '| %s | `%s` | %s | %s |\n' "$label" "$escaped_path" "$bytes" "$modified"
        done
  } > "$output"
done

overview="$atlas_root/Home.md"
{
  echo '---'
  echo 'title: Complete Obsidian Vault Atlas'
  echo "date: $atlas_date"
  echo 'type: vault-atlas-index'
  echo 'status: current organized state'
  echo '---'
  echo
  echo '# Complete Obsidian Vault Atlas'
  echo
  echo "Current inventory generated on $atlas_date after the cross-vault organization. The per-vault notes enumerate every vault-owned folder, file, hidden configuration path, attachment, and symlink. Git object databases are intentionally excluded."
  echo
  echo '| Vault | Folders | Files | Symlinks | Atlas |'
  echo '|---|---:|---:|---:|---|'
  for vault in "${vaults[@]}"; do
    vault_root="$obsidian_root/$vault"
    folders=$(find "$vault_root" -path "$vault_root/.git" -prune -o -type d -print | wc -l)
    files=$(find "$vault_root" -path "$vault_root/.git" -prune -o -type f -print | wc -l)
    links=$(find "$vault_root" -path "$vault_root/.git" -prune -o -type l -print | wc -l)
    printf '| %s | %s | %s | %s | [[%s]] |\n' "$vault" "$folders" "$files" "$links" "$vault"
  done
  echo
  echo '## Scope rules'
  echo
  echo '- `agonizing-sentience` is inventoried but remains structurally independent and excluded from reorganization.'
  echo '- `.git/` is represented by repository status during audits, not by listing its internal objects.'
  echo '- Symlinks are recorded without traversal.'
  echo '- This atlas records the current location and filesystem metadata. Organization reasoning and applied decisions are recorded in [[Organization Findings]].'
} > "$overview"
